export const SET_NEAR_USERS = 'SET_NEAR_USERS';
export const REMOVE_NEAR_USERS = 'REMOVE_NEAR_USERS';
export const UPDATE_NEAR_USERS = 'UPDATE_NEAR_USERS';
export const RESET_NEAR_USERS = 'RESET_NEAR_USERS';
export const UPDATE_INVITE_STATUS_NEAR_USER = 'UPDATE_INVITE_STATUS_NEAR_USER';
export const SENT_INVITE_NEAR_USER = 'SENT_INVITE_NEAR_USER';
export const UNFRIEND_USER = 'UNFRIEND_USER';
export const INIT_NEAR_USERS = 'INIT_NEAR_USERS';