export const INSERT_HISTORY = 'INSERT_HISTORY'
export const UPDATE_INVITE_STATUS_PROFILE_HISTORY = 'UPDATE_INVITE_STATUS_PROFILE_HISTORY';
export const SENT_INVITE_PROFILE_HISTORY = 'SENT_INVITE_PROFILE_HISTORY';
export const UPDATE_UNFRIEND_PROFILE = 'UPDATE_UNFRIEND_PROFILE';
export const UPDATE_PROFILE_HISTORY = 'UPDATE_PROFILE_HISTORY';
export const UPDATE_RECEIVED_INVITE_PROFILE_HISTORY = 'UPDATE_RECEIVED_INVITE_PROFILE_HISTORY';
export const UPDATE_FRIENDS_PROFILES = 'UPDATE_FRIENDS_PROFILES';
export const RESET_HISTORY = 'RESET_HISTORY';