export const INSERT_HISTORY = 'INSERT_HISTORY'
export const UPDATE_INVITE_STATUS_PROFILE_HISTORY = 'UPDATE_INVITE_STATUS_PROFILE_HISTORY';
export const SENT_INVITE_PROFILE_HISTORY = 'SENT_INVITE_PROFILE_HISTORY';
export const RESET_HISTORY = 'RESET_HISTORY';