export const SET_TIMELINE = 'SET_TIMELINE';
export const SET_CUR_PROFILE = 'SET_CUR_PROFILE';
export const UPDATE_TIMELINE_NEAR_USER = 'UPDATE_TIMELINE_NEAR_USER'
export const REMOVE_CUR_PROFILE = 'REMOVE_CUR_PROFILE';