export const SET_USER = 'SET_USER';
export const USER_FETCHED_FAILED = 'USER_FETCHED_FAILED';
export const REMOVE_USER = 'REMOVE_USER';
export const SET_LOCATION = 'SET_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const SET_USER_TIMELINE = 'SET_USER_TIMELINE';
export const UPDATE_PLACES_VISITED = 'UPDATE_PLACES_VISITED';