export const SEND_INVITATION = 'SEND_INVITATION';
export const SET_INVITATIONS = 'SET_INVITATIONS';
export const SET_INVITATIONS_INBOUND = 'SET_INVITATIONS_INBOUND';
export const SET_INVITATIONS_OUTBOUND = 'SET_INVITATIONS_OUTBOUND';
export const UPDATE_INVITATIONS = 'UPDATE_INVITATIONS';
export const RESET_INVITATIONS = 'RESET_INVITATIONS';